project_id = "giucniweqsloezqppsac"

[functions.analyze-phishing]
verify_jwt = false

[functions.geolocate-ip]
verify_jwt = false

[functions.check-dark-web]
verify_jwt = false

[functions.analyze-vishing]
verify_jwt = false

[functions.sandbox-analyzer]
verify_jwt = false